### ISSUE TITLE
Add banner image to WordPress plugin directory

### ISSUE THREAD

**Issue by westonruter** [xwp/wp-widget-customizer#10]
Via [FAQ](http://wordpress.org/plugins/about/faq/):

> **How do I make one of those cool banners for my plugin page?**
> Start by creating an assets/ directory in the root of your SVN checkout. This will be on the same level as tags/ and trunk/, for example.
> 
>  Inside that assets/ directory, you can make a file named "banner-772x250.png" or "banner-772x250.jpg". The image must be exactly 772 pixels wide and 250 pixels tall. No GIFs.
> 
> To support high-DPI (aka "retina") displays, you can additionally make a file named "banner-1544x500.png" or "banner-1544x500.jpg". The image must be exactly 1544 pixels wide and 500 pixels tall. No GIFs. This image, if present, will only be served when the website detects that the viewing browser is on a high-DPI display. Read this feature's announcement post for more details and special notes about creating this image.
> 
> After you check in your new banner(s), it will appear the next time the plugin refreshes itself in the directory. This may take a few minutes.
> 
> For development and testing, you can add a URL parameter to your plugin's URL of "?banner_url=A_LINK_TO_YOUR_IMAGE" to preview what the page will look like with your own image. This will only work with your own plugins, you can not use this parameter on anybody else's plugins.

**Comment by johnregan3** [comment]
@westonruter Here is a first draft on the banner image (just the 772x250 for now):

![banner-772x250](https://f.cloud.github.com/assets/2053940/1133404/d0c138da-1bdc-11e3-8a4a-47790b664b64.png)

**Comment by westonruter** [comment]
@johnregan3 great! Suggestion: could you make the window narrower so that the customizer form appears alongside the widget in the sidebar? I used twentytwelve in the screenshots I made, and with resizing the widget of the window it was easy to get the sidebar and the customizer control to appear side-by-side.

**Comment by johnregan3** [comment]
@westonruter Here's a different version based on your input:

![banner-772x250](https://f.cloud.github.com/assets/2053940/1133542/851c35ee-1bdf-11e3-86d7-bbe1b2f58809.png)

**Comment by westonruter** [comment]
Looks good! What about adding some arrow overlay to indicate that the panel in the left will affect the preview on the right? A rough idea:

![pasted_image_9_12_13_12_47_pm](https://f.cloud.github.com/assets/134745/1133782/460e73f8-1be4-11e3-9592-26af20f7e461.png)

**Comment by johnregan3** [comment]
@westonruter Sounds good.  It gives a visual cue as to what's going on.

![banner-772x250](https://f.cloud.github.com/assets/2053940/1133929/73285dd8-1be7-11e3-85ed-d06923c4f27e.png)

**Comment by johnregan3** [comment]
@westonruter Here's one with some color:

![banner-772x250-bl](https://f.cloud.github.com/assets/2053940/1133996/4fe25c74-1be8-11e3-9d53-8ba9cc4238f1.png)

**Comment by westonruter** [comment]
@johnregan3 Looks really good! I like the color. Only other suggestion I would have is to make the arrow swoop down and then go up to the widget in the sidebar, you know to fill up some of the empty space in the banner.

**Comment by johnregan3** [comment]
@westonruter I see what you're saying.

![banner-772x250-bl](https://f.cloud.github.com/assets/2053940/1134100/5f2185c8-1bea-11e3-816a-586c0ca16516.png)

**Comment by westonruter** [comment]
There we go. Make it so!

**Comment by westonruter** [comment]
@johnregan3 would you mind updating the banner image now to showcase the new collapsable UI you added, and maybe the new drag-and-drop reordering of widgets in the customizer section?

**Comment by johnregan3** [comment]
@westonruter I can do that!

**Comment by johnregan3** [comment]
Starting Point:
![banner-772x250](https://f.cloud.github.com/assets/2053940/1237900/cee39c18-29df-11e3-83b4-995e31720f7c.jpg)

**Comment by westonruter** [comment]
@johnregan3 Great! Love the visualization of the drag-and-drop.
- [ ] I think we can drop the bullet pointed text overlay, as it is obscuring an important company logo :wink: 
- [ ] Could you expand one of the widget controls to show what is inside? 
- [ ] Maybe use another widget than a second Text widget instance.

Other than that, good to go!

**Comment by johnregan3** [comment]
@westonruter  Ver 2: 
![banner-772x250](https://f.cloud.github.com/assets/2053940/1269740/2d6fe3f6-2cfe-11e3-9bb6-35f06db8e963.png)

**Comment by westonruter** [comment]
:boom: commit!
