### ISSUE TITLE
Sidebar terminology 

### ISSUE THREAD

**Issue by raptor235** [xwp/wp-widget-customizer#102]
Has there been discussion on renaming the sidebar word to something more meaningful like widget area... the concept of sidebars has been long gone and widgetized areas should be referred to as such. If anything it causes confusion to end users.

**Comment by westonruter** [comment]
In general, yes. There has been a movement away from the word “sidebar” to use “widget area” instead. 

This Widget Customizer project is now archived since it has been merged into Core, so it shouldn't be used for general discussion. WordPress Trac would be better.
