### ISSUE TITLE
Feature Req: Scroll into view hovered widget

### ISSUE THREAD

**Issue by raptor235** [xwp/wp-widget-customizer#103]
I could see this being very helpful.. if the widget is offscreen scroll to it so the user can see what they're changing... This can be very helpful when you're dealing with a lot of widgets.

**Comment by westonruter** [comment]
Please open an issue on WP Trac: https://core.trac.wordpress.org/

This Widget Customizer plugin is now part of Core and the plugin is no longer being developed separately.
