### ISSUE TITLE
Allow widgets to be edited inline

### ISSUE THREAD

**Issue by westonruter** [xwp/wp-widget-customizer#17]
Instead of having to look up the widget's control in the customizer, what if the widget's form could be brought in alongside the widget itself in the preview? There could be a **Edit** button that appears next to a widget when hovering over it, and when clicking it could make the widget form appear.

**Comment by shaunandrews** [comment]
A quick idea:

![inline-edit](https://f.cloud.github.com/assets/191598/1226704/cb821812-2785-11e3-94af-fc7557e7666e.png)

Do you think the editor should always show up next to the widget itself? What if the user clicks to edit the widgets from within the customizer sidebar?

**Comment by westonruter** [comment]
@shaunandrews wow. I love it!

Regarding what should happen when the user clicks a widget form in the sidebar, here's a crazy idea: what if clicking the collapsed control in the customizer sidebar would simultaneously cause the preview window to scroll so that the widget is in view, while at the same time the widget form would expand and fly out from the sidebar and land next to the widget showing in the preview?

**Comment by shaunandrews** [comment]
I guess that makes sense, since we would be scrolling to show the active widget anyways. I'm a little concern that this is a lot of motion to have. I won't really know for sure until I can play with it and get a first-hand feeling for it all.

**Comment by westonruter** [comment]
Closing this for now. We can revisit later.
