### ISSUE TITLE
Add support for deleting widgets

### ISSUE THREAD

**Issue by westonruter** [xwp/wp-widget-customizer#22]
Just as there is a **Delete** link in the Widgets admin page for eliminating a widget from a sidebar, this same link should be in the widget form customizer control.

Relates to #3 (adding widgets)

Note that the widget control form currently hides the **Delete** button since it is not currently implemented:

![pasted_image_10_8_13_10_18_am](https://f.cloud.github.com/assets/134745/1289641/c6ce005e-3024-11e3-995c-3c50ba745eed.png)

**Comment by TrevorMills** [comment]
@westonruter that commit does not reflect this issue.  Please ignore.  It was a brain fart moment.

**Comment by westonruter** [comment]
@TrevorMills ok :smile:

By the way, I updated the description in this issue to include a screenshot depicting what is going on with the hidden Delete link in the widget control form.

**Comment by TrevorMills** [comment]
@westonruter coolio.  I'm working on this one now.  Commit 3f0c41e actually reflects issue #26.

**Comment by TrevorMills** [comment]
@westonruter why are you using custom code to update the widget instead of routing through the same function that the main widgets page uses to update widgets?  I see the note about copying most of the code from wp_ajax_save_widget

**Comment by westonruter** [comment]
@TrevorMills because we don't want to actually update the widget in the DB. We only want to [execute](https://github.com/x-team/wp-widget-customizer/blob/master/widget-customizer.php#L376) the widget's `update` callback so that the previewed `$instance` will get processed, and then to [call](https://github.com/x-team/wp-widget-customizer/blob/master/widget-customizer.php#L399) the widget's `form` callback so that the widget form in the preview can be refreshed with the previewed `$instance`. All of this is done without saving anything to the DB, which is what `wp_ajax_save_widget` does, and this is why we can't re-use it.

**Comment by TrevorMills** [comment]
Ah, right, so the changes don't actually go to the DB until the "Save & Publish" button is hit, correct?

**Comment by westonruter** [comment]
@TrevorMills exactly. This conversation reminded me of something else needing to be done related to saving settings. Added #28.

**Comment by westonruter** [comment]
@TrevorMills @shaunandrews: how widget “deletion” now looks in the customizer, which is actually now trashing since the widgets are just moved to the Inactive Widgets sidebar:

![screenshot-4](https://f.cloud.github.com/assets/134745/1340004/3315c056-361c-11e3-8ad7-20f47a7714dd.png)
