### ISSUE TITLE
Add unit tests

### ISSUE THREAD

**Issue by westonruter** [xwp/wp-widget-customizer#25]

**Comment by gedex** [comment]
@westonruter I'm going to work on this unless someone has started?

**Comment by westonruter** [comment]
@gedex :heart: no one has, good for you!! You might want to wait until #3 is merged, as it will contain a lot of code changes to enable new widgets to be added while in the preview.

**Comment by gedex** [comment]
@westonruter Ok I'll wait until #3 is merged.

**Comment by westonruter** [comment]
@gedex or you can branch your unit tests off of `issue-3-addition`

**Comment by westonruter** [comment]
Great work @gedex! Thank you for spearheading unit testing.
