### ISSUE TITLE
Feature link to Customizer on the Widgets admin page

### ISSUE THREAD

**Issue by westonruter** [xwp/wp-widget-customizer#29]
After the plugin has been enabled, users may not be aware that widgets can be edited in the customizer. So there should be a prominent link to open the customizer, placed somewhere on the page.

**Comment by johnregan3** [comment]
PR submitted https://github.com/x-team/wp-widget-customizer/pull/31

I'm open to suggestions, if you have any, @westonruter

**Comment by westonruter** [comment]
@johnregan3 please open the PR to the `develop` branch instead.

**Comment by westonruter** [comment]
@johnregan3 well, nevermind, I'll merge it manually. But merge it into `develop` in the future.

**Comment by westonruter** [comment]
Thanks @johnregan3! Will be part of next release.

![widgets__wordpress_develop__wordpress-3](https://f.cloud.github.com/assets/134745/1315309/f26004ee-3284-11e3-8fc3-6428e8939c4f.png)

**Comment by johnregan3** [comment]
:+1:
