### ISSUE TITLE
Change widget control form button from Save to Update

### ISSUE THREAD

**Issue by westonruter** [xwp/wp-widget-customizer#40]
Change button from Primary to Secondary.

**Comment by bobbravo2** [comment]
Agreed - it should be class=secondary - and update - the current implementation is unclear about whether or not what I'm doing is "going live". Changing the button to update is much clearer.

**Comment by westonruter** [comment]
Done:

![screen_shot_2013-10-26_at_3 27 18_pm-3](https://f.cloud.github.com/assets/134745/1414528/fc49eac8-3e8d-11e3-8492-f9881e98553c.png)
