### ISSUE TITLE
Improve widget addition dropdown with autocomplete and searching

### ISSUE THREAD

**Issue by westonruter** [xwp/wp-widget-customizer#55]
See [comment](https://github.com/x-team/wp-widget-customizer/pull/3#issuecomment-27137585) in #3, from @bobbravo2:

> love the drop down for adding new widgets - that's what I was hoping for. What do you think about adding the Chosen jQuery plugin to enhance it with search (search a widget's description / title / possible alternate keywords for new users)?

**Comment by westonruter** [comment]
@bobbravo2 yes, I'd love to add Chosen or [Select2](http://ivaynberg.github.io/select2/) to improve the usability of the dropdown. From the Chosen demo, I assume the Standard Select or the Standard Select with optgroup would be the field we'd be interested in? I guess too we'll want to let the autocomplete match not only the title of the widget, but its description as well?

**Comment by bobbravo2** [comment]
@westonruter My thinking EXACTLY! RE: Chosen: I think the standard select should work fine - it's an amazing plugin. Not sure we'd need an optgroup - unless we want to also add "hidden widgets" - then it'd make sense. RE: Autocomplete - yes, I totally agree - we want to make it super easy for people to find widgets - searching title + description is a great first step.

**Comment by westonruter** [comment]
This is being addressed in #58
