### ISSUE TITLE
Improve scrolling widget into view

### ISSUE THREAD

**Issue by westonruter** [xwp/wp-widget-customizer#56]
The [current `scrollIntoView`](https://github.com/x-team/wp-widget-customizer/blob/97cbfc58eac8d2b6946f0fe5727cac23958721b0/widget-customizer.js#L558-L568) is woefully inadequate.

Builds on and #5 and #13

**Comment by bobbravo2** [comment]
My personal favorite is 

```
$('html, body').animate({scrollTop: $(elem).offset().top }, 250);
```

**Comment by westonruter** [comment]
@bobbravo2 I think that is what we had initially, but I was concerned that it wouldn't work if the widget was inside of another scrolling container. The animation to scroll into view should not get invoked if the widget can already be seen. So we need logic to detect if the widget is currently in view to begin with.

**Comment by westonruter** [comment]
Moved to Trac: https://core.trac.wordpress.org/ticket/27358
