### ISSUE TITLE
Fix padding for widget forms controls

### ISSUE THREAD

**Issue by westonruter** [xwp/wp-widget-customizer#57]
![image](https://f.cloud.github.com/assets/134745/1616601/67f2d66c-560e-11e3-96cf-8fd81e3e3429.png)

**Comment by kucrut** [comment]
@westonruter I'm not seeing this padding in the master branch (and the custom select for that matter).

**Comment by westonruter** [comment]
@kucrut you have to be on WordPress 3.8 (or trunk) to see it.

**Comment by westonruter** [comment]
The select is not custom either, it's just the native style for controls in OS X :smile:

**Comment by kucrut** [comment]
@westonruter By _custom select_ I meant the _Archive_ dropdown in the screenshot above, which is actually not a `select` element :wink: 

So, which padding are we supposed to fix here?

**Comment by westonruter** [comment]
@kucrut right :smile: So the collapsable widget control. 

The fix is to add the necessary `padding` so that the widget form control appears in the customizer the same way that it appears on the widgets admin page.

**Comment by alexvornoffice** [comment]
the same problem, just download the latest nightly build

**Comment by alexvornoffice** [comment]
![n](https://f.cloud.github.com/assets/1689187/1699821/ec250b18-5fc7-11e3-9e0f-3b4520b1f595.png)
