### ISSUE TITLE
Add widget JS bugs (Firefox)

### ISSUE THREAD

**Issue by kucrut** [xwp/wp-widget-customizer#62]
- [ ] First widget can't be added
- [ ] Clicking on the right side of widgets dropdown after hovering over dropdown options will add the last hovered option (not happening in Firefox Nightly)

**Comment by westonruter** [comment]
This will probably be invalidated by #58 which gets rid of the `select` altogether.

/cc @shaunandrews

**Comment by westonruter** [comment]
@kucrut can you confirm that #58 invalidates this issue?

**Comment by kucrut** [comment]
@westonruter Yes.
