### ISSUE TITLE
Show widget form controls initially in collapsed state

### ISSUE THREAD

**Issue by westonruter** [xwp/wp-widget-customizer#7]
Since all widget form controls are shown in full when the customizer section is expanded, it can take up a lot of room and make it difficult to navigate to the desired widget. So they should all be presented in a minimized state, though not like an accordion since we want to be able to have multiple widget controls open at a time.

**Comment by johnregan3** [comment]
@westonruter Could this be an accordion that allows you to have multiple panels open?

**Comment by westonruter** [comment]
@johnregan3 sure! Is that an option with the accordion library used in core? I was thinking it might be nice to replicate this UI:

![widgets__local_wordpress_trunk_dev__wordpress](https://f.cloud.github.com/assets/134745/1133755/cd473108-1be3-11e3-9976-a836310b803d.png)

**Comment by johnregan3** [comment]
@westonruter That looks good.  I always try to use WP UI.  I'd like to take a stab at this one.

**Comment by westonruter** [comment]
@johnregan3 go for it!

**Comment by johnregan3** [comment]
@westonruter I'm still working out how to add a PR to an issue via hub.  In the meantime, you can review my PR at https://github.com/x-team/wp-widget-customizer/pull/12
