### ISSUE TITLE
Fade out sidebar sections that lack any rendered widgets

### ISSUE THREAD

**Issue by westonruter** [xwp/wp-widget-customizer#76]
Suggestion from @tomdryan:

> Also, it would be nice if the title of sidebars was greyed out or had some other indication that it does not contain any widgets

So basically this would do for the sidebar section title what was done for the widget titles which aren't rendered on the current page. See #65.

**Comment by tomdryan** [comment]
Exactly. Thanks Weston!

**Comment by westonruter** [comment]
Moved to Trac: https://core.trac.wordpress.org/ticket/27405
