### ISSUE TITLE
Group all sidebars under one customizer section

### ISSUE THREAD

**Issue by westonruter** [xwp/wp-widget-customizer#77]
Suggestion from @tomdryan:

> Would it be possible to have a singe "Widgets" category that you would expand to show all the widgets? Right now, there could be 10+ different widgets listed and it makes the customer menu very busy.
> 
> So right now I'm seeing "Logo", 5 widget categories, "Desgn", "Colors", etc. I'm suggesting that there is only ever one "Widget" selectiion inthe customizer and when you expand that, then you will see all the sidebard like you do now. That would keep the customizer cleaner -- not everyone want to play with widgets all day. :)

**Comment by westonruter** [comment]
From @melchoyce:

![Screencast](https://i.cloudup.com/vQKSAVfXlL.gif)

**Comment by tomdryan** [comment]
That's it. A picture is worth a thousand (of my) words. Thanks!

**Comment by westonruter** [comment]
I think this kind of 3rd level of organization would be great for the Customizer in general. There should be a way to group customizer sections logically.

**Comment by shaunandrews** [comment]
Heh.

http://www.shaunandrews.com/themes/new-customizer/

Played with this concept a few months ago. Still think it's a good direction. 

## 

Shaun

**Comment by melchoyce** [comment]
Aha! That's what I was trying to remember. I knew you'd done something with this concept at some point. Thanks. :)

**Comment by tomdryan** [comment]
There are a few side benefits of doing it this way: 
1. The customizer menu will load more quickly (there is a noticeable delay for me for the sidebar menu items to load) 
2. You no longer have to label the sidebar "Widgets: Sidebar Label"  much cleaner

**Comment by tomdryan** [comment]
Doing it this way also eliminates the need for a separate fly out menu for adding widgets. Nice!

**Comment by westonruter** [comment]
This topic was discussed today on the weekly #wordpress-dev chat: https://irclogs.wordpress.org/chanlog.php?channel=wordpress-dev&day=2014-01-29&sort=asc#m780233

**Comment by westonruter** [comment]
I think I figured out the way to do go about this, from a customizer technical perspective. Currently there is a separate customizer control for each sidebar and for each widget in each sidebar. So there is a mapping of one setting per control. However, if we were to merge the two controls into one widget area control, and associated multiple settings with that one control, then we'd be able to just have one single "Widgets" customizer section, and this section would be populated with these Widget Area controls. Each widget area control then could have each individual widget control appear inside of it: so we'd have our 3 levels. And when expanding the "Widgets" section, we could make it fly out as shown in @shaunandrews's prototype, instead of expand down as normal.

**Comment by westonruter** [comment]
Moved to Trac: https://core.trac.wordpress.org/ticket/27406
