### ISSUE TITLE
Improve styling of widget search field

### ISSUE THREAD

**Issue by westonruter** [xwp/wp-widget-customizer#83]
Feedback from Nacin for things to address:

> the unique styling of the search field

**Comment by westonruter** [comment]
Discussed today on [#wordpress-ui](https://irclogs.wordpress.org/chanlog.php?channel=wordpress-ui&day=2014-02-10&sort=asc#m157256)

**Comment by westonruter** [comment]
New styling from @shaunandrews:

> ![image](https://f.cloud.github.com/assets/134745/2130445/f42ec972-9292-11e3-831a-99648f2ea6b6.png)

**Comment by shaunandrews** [comment]
I can't figure out this git stuff, so here's a diff:

https://cloudup.com/c1INl2imMdI

**Comment by westonruter** [comment]
@shaunandrews cheers! Looks awesome.
