### ISSUE TITLE
Wide widgets, position fixed + flexible widget height = usability issue

### ISSUE THREAD

**Issue by PeterKnight** [xwp/wp-widget-customizer#98]
The current solution for wide widgets relies on settings the widget form container to position fixed. If the widget form happens to be taller than the viewport height, the user can't actually navigate the full form. The work around I guess is for plugin authors to create a scroll type css workaround themselves?

I really dislike the current state of wide widgets in the customizer. Having it stuck in its default position with no regard where the widget is in the preview or what the actual dimensions are of the widget controls creates an ugly user experience. 

Below is an example with a widget that has repeating field groups, so the height expands.
![wide-widgets-ui-issues](https://f.cloud.github.com/assets/906292/2341063/6d3f12c8-a4d0-11e3-9b88-c5872a805b87.jpg)

**Comment by westonruter** [comment]
@PeterKnight You should open issues in Trac now. Further development will not happen on the GitHub repo.

**Comment by westonruter** [comment]
This issue was just reported in Trac: https://core.trac.wordpress.org/ticket/27348

**Comment by westonruter** [comment]
@PeterKnight here's a core patch which introduces scrollbars for widgets taller than the window: https://github.com/x-team/wordpress-develop/compare/trac-27348
